### ISSUE TITLE
Add clientside "passed" and "failed" filters to test results page

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-test-suite#79] opened 2016-03-11 02:31 UTC
It can be annoying to scroll through hundreds of passing tests to find the couple failing ones. One solution is to add some Javascript-powered filters to the page. By default we would only show failing tests.

**Comment by jfirebaugh** [comment] 2016-03-11 04:48
Duplicate of #67.

**Closed by jfirebaugh** 2016-03-11 04:48 UTC
